version: 2

project_name: config

before:
  hooks:
    - go mod tidy

builds:
  - id: config
    binary: config
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - config
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

nfpms:
  - id: linux-packages
    ids:
      - config
    package_name: config
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: DannyBen
    homepage: https://github.com/DannyBen/config
    maintainer: Danny Ben Shitrit <db@dannyben.com>
    description: CLI for reading and editing configuration files.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: "0.0.0-snapshot-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    include:
      - "^- "

release:
  draft: false
